### ISSUE TITLE
Handling Missing Values

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/genefilter#1]
Is there a possibility of inputting missing values and producing a test statistic without adversely affecting the performance of the function? It would be undesirable to remove from analysis a gene such as

```r
library(genefilter)
abundances <- matrix(c(4.5, 5.2, 5.0, 4.1, 5.5, 5.1, 9.6, 10.0, 9.1, NA, 11.0), ncol = 10, byrow = TRUE)
classes <- factor(rep(c("Healthy", "Disease"), each = 5))
rowttests(abundances, classes)
```

which can have a significantly large t-statistic calculated using `t.test`.

**Comment by mtmorgan** [comment]
I think this can be implemented...I'll let you know.
