### ISSUE TITLE
Sweave2Rmd

### ISSUE THREAD

**Issue by kahvecirem** [Bioconductor/genefilter#7]
Hi,
   I'm volunteering with [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd) and we're trying to replace all Bioconductor Sweave vignettes R Markdown vignettes. Would you be willing to accept a pull request with the R Markdown version of genefilter (vignette_name) from one of our volunteers? We'll ask you to review and accept the pull request. You'll also need to bump the version number in your DESCRIPTION file so that the build machines will recognize that a new version is available.
   Thanks for your time.

**Comment by lshep** [comment]
This is a Bioconductor core team maintained package so I don't think you needed to ask permission as we gladly accept the help in conversion.  Please note there is one PR for one of the vignettes already so only the other two would need to be converted.
